version: '3'

services:

  app:
    image: 'sinicize/canvas-app:${CANVAS_VERSION}'
    build:
      context: '../../'
      dockerfile: 'sinicize/docker/canvas_app.docker'
      args:
        CANVAS_VERSION: ${CANVAS_VERSION}
        CANVAS_DB_HOST: ${CANVAS_DB_HOST}
        CANVAS_DB_NAME: ${CANVAS_DB_NAME}
        CANVAS_DB_USERNAME: ${CANVAS_DB_USERNAME}
        CANVAS_DB_PASSWORD: ${CANVAS_DB_PASSWORD}
        CANVAS_ENCRYPTION_KEY: ${CANVAS_ENCRYPTION_KEY}

  daemon:
    image: "sinicize/canvas-daemon:${CANVAS_VERSION}"
    depends_on:
      - "app"
    build:
      context: "."
      dockerfile: "daemon.docker"
      args:
        CANVAS_VERSION: ${CANVAS_VERSION}

  web:
    image: "sinicize/canvas-web:${CANVAS_VERSION}"
    depends_on:
      - "app"
    build:
      context: "."
      dockerfile: "web.docker"
      args:
        CANVAS_VERSION: ${CANVAS_VERSION}
