# 不适用集群，单机运行
version: "3"

services:
  app:
    image: "${DOCKER_REGISTRY}/canvas-app:${CANVAS_VERSION}"
    env_file: env_file
    depends_on:
      - redis
    volumes:
#      - "/opt/canvas/files:/opt/canvas/tmp/files"
      - "canvas-file:/opt/canvas/tmp/files"
      - "canvas-public:/opt/canvas/public"
      - "/opt/canvas/config:/opt/canvas/sinicize/config:ro"
      - "/opt/canvas/config/database.yml:/opt/canvas/config/database.yml:ro"
      - "/opt/canvas/config/security.yml:/opt/canvas/config/security.yml:ro"

  daemon:
    image: "${DOCKER_REGISTRY}/canvas-daemon:${CANVAS_VERSION}"
    env_file: env_file
    depends_on:
      - redis
    volumes:
#      - "/opt/canvas/files:/opt/canvas/tmp/files"
      - "canvas-file:/opt/canvas/tmp/files"
      - "canvas-public:/opt/canvas/public"
      - "/opt/canvas/config:/opt/canvas/sinicize/config:ro"
      - "/opt/canvas/config/database.yml:/opt/canvas/config/database.yml:ro"
      - "/opt/canvas/config/security.yml:/opt/canvas/config/security.yml:ro"
      - "/opt/canvas/config/delayed_jobs.yml:/opt/canvas/config/delayed_jobs.yml:ro"

  web:
    image: "${DOCKER_REGISTRY}/canvas-web:${CANVAS_VERSION}"
    env_file: env_file
    depends_on:
      - app
    volumes:
      - "canvas-public:/opt/canvas/public:ro"
      - "./web/sites-enabled:/etc/apache2/sites-enabled"
    ports:
      - "80:80"

  redis:
    image: "redis:3"

volumes:
  canvas-file:
    external: true
  canvas-public:
    external: true
